// AUTO-GENERATED by scripts/generate-component-ids.mjs — do not edit by hand.
// Source: src/components/**/*.tsx · Regenerate: npm run component-ids

/**
 * Every component `src/components` contains, addressed `folder/Name`.
 *
 * The address is the app's own and is the same string on both sides of the seam:
 * the gallery's entry, the workbench's reference row, and `?c=` between the two
 * sites. The platform suffix is deliberately not part of it — `ReaderView.tsx`
 * and `ReaderView.web.tsx` are one member here.
 *
 * `src/gallery/catalogue.tsx` is typed against this union, so a component added
 * to `src/components` stops the app compiling until it has an entry or a written
 * reason not to have one.
 */
export type ComponentId =
  | 'discover/ProjectRow'
  | 'discover/SampleHitRow'
  | 'discover/SearchEntry'
  | 'discover/TopicRail'
  | 'feed/ArticleHero'
  | 'feed/ArticleRow'
  | 'feed/FaktencheckRail'
  | 'gate/LoginGate'
  | 'home/BackstageTeaser'
  | 'home/CalloutTeaser'
  | 'home/EarlyAccessCard'
  | 'home/HomeHeader'
  | 'home/ImpactFooter'
  | 'home/MediathekReihe'
  | 'home/SpotlightBriefing'
  | 'keyboard/KeyboardAvoiding'
  | 'media/EpisodeRow'
  | 'media/LiveBanner'
  | 'media/MediaCard'
  | 'media/SeriesTile'
  | 'media/VideoFrame'
  | 'participate/CalloutCard'
  | 'participate/ClaimStatusTag'
  | 'participate/FormField'
  | 'player/MiniPlayer'
  | 'player/ProgressBar'
  | 'profile/ClubCard'
  | 'profile/NavCard'
  | 'profile/SettingRow'
  | 'reader/ReaderView'
  | 'recovery/RecoveryScreen'
  | 'ui/Badge'
  | 'ui/Bleed'
  | 'ui/Button'
  | 'ui/Card'
  | 'ui/Chip'
  | 'ui/Hairline'
  | 'ui/Overline'
  | 'ui/Rail'
  | 'ui/SafeAreaView'
  | 'ui/ScaledText'
  | 'ui/ScaledTextInput'
  | 'ui/Screen'
  | 'ui/ScreenHeader'
  | 'ui/ScreenHeaderBar'
  | 'ui/SectionCard'
  | 'ui/SectionHeader'
  | 'ui/SplitRow'
  | 'ui/Thumbnail'
  | 'ui/Typo';
