/**
 * Where every fact in this repository comes from, read off the repository.
 *
 * The working method here is that the code is the documentation: as much as can
 * be is produced from the sources, because prose written about a codebase goes
 * stale quietly and nothing goes red. The measures for that are real and spread
 * across the tree, and until this file the only place they were described was a
 * chat message, which is itself the kind of prose that goes stale.
 *
 * So this file scans rather than asserts. The generated files are found by the
 * marker they carry, their generators by the write calls that name them, the
 * checks by reading the test files, and the weak spots by crossing those three
 * sets. A page that listed them by hand would be the next typed fact to drift,
 * and it would be the one claiming the others cannot.
 *
 * What IS typed here is the argument: why a generated fact beats a read one and a
 * read one beats a pinned one, and why two of the weakest arrangements in the
 * repository are deliberate. That part is a judgement and no scan produces it.
 * Every path, count, command and quotation around it is read at build time.
 */
import { execFileSync } from 'node:child_process';
import { closeSync, openSync, readFileSync, readSync, statSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';

import { DOCUMENTS, isRecordFile, type DocumentSource } from './registry.ts';

/**
 * Where this page answers, and what it is called.
 *
 * `file` is the honest answer to "where does this page live": there is no
 * Markdown behind it, so it names the program that writes it. `pages/Document.tsx`
 * reads `generated` and says so in the footer rather than offering an edit to a
 * file nobody should edit by hand.
 */
export const PROVENANCE_SOURCE: DocumentSource = {
  id: 'provenance',
  file: 'apps/workbench/plugin/provenance.ts',
  route: '/provenance',
  nav: 'Provenance',
  blurb:
    'Which facts here are generated, which are read in place, which are only pinned, and where that fails.',
};

/** `apps/workbench/plugin` back up to the root, so a link can be written from there. */
const UP = '../'.repeat(dirname(PROVENANCE_SOURCE.file).split('/').length);

/**
 * How far into a file the marker has to appear.
 *
 * A generated file announces itself in its header or not at all, and one of them
 * is 642 KB on 24 lines. Reading the first few hundred bytes of every tracked
 * file is a scan; reading all of them is four megabytes of base64 for nothing.
 */
const HEAD_BYTES = 640;

/** Only the files that can carry a comment, which is where a marker goes. */
const SCANNABLE = /\.(ts|tsx|mts|mjs|cjs|js|css|json|md|yml|yaml)$/;

/**
 * A file that says it was generated.
 *
 * Three spellings are in the tree and all three are matched here rather than
 * normalised in the files: `AUTO-GENERATED by <script>`, `GENERATED by <script>`,
 * and the sentence Uniwind writes into the type shims it owns. What they have in
 * common is the only thing this needs — a claim, in the file itself, that editing
 * it is pointless.
 */
const MARKER =
  /(?:AUTO-)?GENERATED by ([^\s—,;.]+)|This file is generated by (\w+) and it should not be edited/i;

/** `Regenerate: npm run tokens`, which most of the markers carry and is the useful half. */
const REGENERATE = /Regenerate:\s*(npm run [\w:-]+)/i;

/** A quoted path with at least one directory in it, which is what a script writes to. */
const PATH_LITERAL = /['"`]([\w./@-]+)['"`]/g;

export interface GeneratedFile {
  /** Repository-relative path. */
  file: string;
  bytes: number;
  lines: number;
  /** The marker's own words, as the file writes them. */
  marker: string;
  /** What the marker names as its author. */
  claims: string;
  /** A script in this repository whose write call names this file, or null. */
  writtenBy: string | null;
  /** The command that re-takes it, from the marker or from a `package.json`. */
  command: string | null;
  /** Test files that name this path, which is what keeps a committed copy honest. */
  checkedBy: string[];
}

export interface WrittenFile {
  file: string;
  writtenBy: string;
  command: string | null;
}

/** One test that opens a file in the tree and holds something typed to what it finds. */
export interface PinnedCheck {
  file: string;
  /** `it(...)` and `test(...)` cases in it. */
  cases: number;
  /** The tracked files and directories it reaches for. */
  reads: string[];
  /**
   * What each case is called.
   *
   * A case title is a sentence somebody wrote beside the assertion, so it says
   * what is being held better than any description of the file could, and it is
   * read rather than restated.
   */
  titles: string[];
}

/** A document this site publishes, and what holds its prose to anything. */
export interface DocumentPin {
  file: string;
  route: string;
  pinnedBy: string[];
}

export interface Provenance {
  /** Files that announce themselves as generated. */
  generated: GeneratedFile[];
  /** Files a script writes that say nothing about it. */
  unmarked: WrittenFile[];
  /** Files that claim to be generated and that nothing in the tree writes. */
  orphaned: GeneratedFile[];
  documents: DocumentPin[];
  records: number;
  /** What the decisions ledger has recorded, which only ever grows. */
  ledger: { records: number; decisions: number; texts: number; slugs: number };
  pinned: PinnedCheck[];
  tests: { files: number; cases: number };
  /** The `npm run check` figures, as the one document that holds them writes them. */
  checkDuration: string | null;
  /** The sources workflow's schedule, off the workflow. */
  sourcesCron: string | null;
  /** The command the decisions test compares the ledger against. */
  ledgerGuard: string | null;
  /** The interface the diagrams test parses, and the call it parses it with. */
  portsRead: { file: string; interface: string; api: string } | null;
  /** What `Services.tsx` claims about the sources, which nothing checks. */
  servicesClaim: string | null;
}

/** The measurement is the same for one build, and the test files ask for it repeatedly. */
const CACHE = new Map<string, Provenance>();

export function buildProvenance(root: string): Provenance {
  const cached = CACHE.get(root);
  if (cached) return cached;
  const built = scan(root);
  CACHE.set(root, built);
  return built;
}

/** The last two segments of a path, which is enough to tell two `theme.css` apart. */
function tailOf(file: string): string {
  return file.split('/').slice(-2).join('/');
}

/** The first two segments, which in this repository is the workspace a file lives in. */
function packageOf(file: string): string {
  return file.split('/').slice(0, 2).join('/');
}

/** Every tracked file, which is also every file a reader of the repository has. */
function tracked(root: string): string[] {
  return execFileSync('git', ['ls-files'], { cwd: root, encoding: 'utf8', maxBuffer: 1 << 26 })
    .split('\n')
    .filter(Boolean);
}

/** The first bytes of a file, without reading 642 KB of base64 to learn it has no header. */
function head(path: string): string {
  const fd = openSync(path, 'r');
  try {
    const buffer = Buffer.alloc(HEAD_BYTES);
    const read = readSync(fd, buffer, 0, HEAD_BYTES, 0);
    return buffer.subarray(0, read).toString('utf8');
  } finally {
    closeSync(fd);
  }
}

/**
 * Which file a script writes, decided by the write call and not by a mention.
 *
 * A script that merely READS `theme.css` must not be reported as writing it, and
 * one exists to do exactly that: `scripts/tokens-source.mjs` resolves that file
 * for every consumer. So what is collected is the text of every write call,
 * with the identifiers in it expanded once from their own declarations, and the
 * candidate file is matched against that. `writeFile(OUT, …)` beside `const OUT =
 * join(WORKBENCH, 'content/sources.measured.ts')` resolves; `readFileSync(
 * THEME_CSS_PATH)` resolves to nothing, because it is not a write.
 *
 * A window rather than the first argument, because `writeFileSync(resolve(SRC,
 * 'tokens.generated.ts'), …)` puts the name inside a call whose comma comes
 * first, and cutting at that comma threw away every path written that way.
 */
function writeTargets(source: string): Set<string> {
  const constants = new Map<string, string>();
  const declaration = /(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([^;]{0,240})/g;
  for (const hit of source.matchAll(declaration)) constants.set(hit[1], hit[2]);

  let text = '';
  // To the end of the statement, because a call is written over four lines as
  // often as over one — and no further, or the read on the line below it is
  // swept in as a write. That is how `tokens/theme.css`, which this repository
  // vendors and only ever reads, was reported as generated.
  for (const hit of source.matchAll(/write(?:File)?(?:Sync)?\s*\(([^;]{0,240})/g)) {
    text += ` ${hit[1]}`;
    for (const name of hit[1].matchAll(/[A-Za-z_$][\w$]*/g)) {
      const value = constants.get(name[0]);
      if (value !== undefined) text += ` ${value}`;
    }
  }

  // The quoted path segments only, never the surrounding text. The header a
  // generator writes INTO its output is an argument of the same write call, and
  // those headers name other files: `apps/mobile/src/lib/platform/expo.ts` was
  // reported as generated because the podcast bundle's header mentions it.
  return new Set([...text.matchAll(PATH_LITERAL)].map((hit) => hit[1]));
}

/**
 * A test that opens a file in the repository, which is the whole of tier three.
 *
 * A behaviour test needs no filesystem. One that reaches for it is reading the
 * source to hold something to it — a document's sentence, a constant typed in
 * another package, a generated file that must still be what its generator emits.
 */
const OPENS_A_FILE =
  /\b(?:readFileSync|readdirSync|existsSync|statSync|execFileSync|execSync)\s*\(/;

/**
 * Whether a line reaches for a file, rather than mentioning one.
 *
 * Both happen constantly in this repository's tests: a docstring names the file
 * whose bug it records, and the line below it reads something else entirely.
 * Counting the first would put a dozen checks under `AGENTS.md` when one of them
 * opens it, which is the flattering answer and the wrong one.
 */
const READS = /\b(?:read|readdir|exists|stat|exec|join|resolve|source)\w*\s*\(/;

/** Every `package.json` script, as the command a person types against what it runs. */
function npmScripts(root: string, files: string[]): { command: string; runs: string }[] {
  const all: { command: string; runs: string }[] = [];
  for (const file of files) {
    if (basename(file) !== 'package.json') continue;
    const json = JSON.parse(readFileSync(join(root, file), 'utf8')) as {
      scripts?: Record<string, string>;
    };
    for (const [name, runs] of Object.entries(json.scripts ?? {})) {
      all.push({ command: `npm run ${name}`, runs });
    }
  }
  return all;
}

function scan(root: string): Provenance {
  const files = tracked(root);
  const paths = new Set(files);

  /*
   * The scripts that could have written something: `scripts/` in any workspace,
   * plus `tools/`, where the Figma plugin's generators live. Not the whole tree —
   * a page that named a file as its own generator because the file mentions
   * itself would be worse than no answer at all.
   */
  const targets = new Map<string, Set<string>>();
  for (const file of files) {
    if (!/\.(mjs|mts|ts|js)$/.test(file)) continue;
    if (!/(^|\/)scripts\//.test(file) && !file.startsWith('tools/')) continue;
    targets.set(file, writeTargets(readFileSync(join(root, file), 'utf8')));
  }

  const runnable = npmScripts(root, files);
  const tests = files.filter((file) => /\.test\.tsx?$/.test(file));
  const testText = new Map(tests.map((file) => [file, readFileSync(join(root, file), 'utf8')]));

  /*
   * The tail, then the basename. Two tracked files are called `theme.css` — the
   * vendored source and the file generated from it — and two are called
   * `offlineBundle.generated.ts`, so a write call naming only the basename has to
   * be allowed to match one of them without claiming the other as well. The tail
   * is tried first for that reason, and the bare basename only where it belongs
   * to one file in the repository, or where the file's own marker already named
   * the script being asked about.
   */
  const ambiguous = new Set<string>();
  const seen = new Set<string>();
  for (const file of files) {
    const name = basename(file);
    if (seen.has(name)) ambiguous.add(name);
    seen.add(name);
  }

  /** Whether a path a script writes to is this file, written from wherever it stands. */
  const names = (literal: string, file: string, exactly: boolean): boolean => {
    const tail = tailOf(file);
    const name = basename(file);
    if (literal === file || literal === tail || literal.endsWith(`/${tail}`)) return true;
    if (exactly || ambiguous.has(name)) return false;
    return literal === name || literal.endsWith(`/${name}`);
  };

  /** The script a marker names, if the tree still holds a script by that name. */
  const claimed = (claims: string): string | null =>
    [...targets.keys()].find((script) => script.replace(/\.\w+$/, '').endsWith(claims)) ?? null;

  const writerOf = (file: string, claims: string | null, exactly = false): string | null => {
    // The file says who wrote it, so the question is only whether that script
    // really writes something by this name. A verified claim, not a guess, and
    // the one place a basename shared by two files is allowed to settle it.
    const named = claims === null ? null : claimed(claims);
    const own = named === null ? new Set<string>() : (targets.get(named) ?? new Set<string>());
    const name = basename(file);
    if (named !== null && [...own].some((l) => names(l, file, false) || l === name)) return named;

    for (const [script, written] of targets) {
      if (script === file) continue;
      if ([...written].some((literal) => names(literal, file, exactly))) return script;
    }
    return null;
  };

  const commandFor = (file: string, script: string | null): string | null => {
    for (const { command, runs } of runnable) {
      if (script !== null && runs.includes(basename(script))) return command;
      if (runs.includes(tailOf(file))) return command;
    }
    return null;
  };

  /**
   * A command that writes the file itself, for an artefact no script in the tree
   * writes: `formatjs extract … --out-file ../../packages/catalogue/src/en.json`. The
   * output flag is required, or every `node scripts/adr.mjs new` would be read as
   * writing the script it runs.
   */
  const commandWriting = (file: string): { command: string; runs: string } | null =>
    runnable.find(({ runs }) => new RegExp(`--out\\S*[= ]\\S*${tailOf(file)}`).test(runs)) ?? null;

  const checkedBy = (file: string): string[] => {
    const tail = tailOf(file);
    const name = basename(file);
    return tests.filter((test) => {
      const text = testText.get(test) ?? '';
      // A test inside the same workspace names its own package's artefact by
      // its bare name, and that is not the ambiguity the rule above guards
      // against: `drift.test.ts` listing `theme.css` can only mean the one
      // beside it.
      const near = packageOf(test) === packageOf(file);
      return text.includes(tail) || ((near || !ambiguous.has(name)) && text.includes(name));
    });
  };

  const generated: GeneratedFile[] = [];
  const unmarked: WrittenFile[] = [];

  for (const file of files) {
    if (!SCANNABLE.test(file)) continue;
    const path = join(root, file);
    const first = head(path);
    const marked = MARKER.exec(first);

    if (marked) {
      const claims = marked[1] ?? marked[2];
      const writtenBy = writerOf(file, marked[1] ?? null);
      generated.push({
        file,
        bytes: statSync(path).size,
        lines: readFileSync(path, 'utf8').split('\n').length,
        marker:
          first
            .split('\n')
            .find((line) => MARKER.test(line))
            ?.replace(/^[\s*/]+/, '')
            .trim() ?? '',
        claims,
        writtenBy,
        command: REGENERATE.exec(first)?.[1] ?? commandFor(file, writtenBy),
        checkedBy: checkedBy(file),
      });
      continue;
    }

    /*
     * A file a script writes and that says nothing about it. JSON cannot carry a
     * comment, which is most of this list and is a reason rather than an excuse:
     * a marker is what tells somebody opening the file that editing it is a
     * wasted afternoon, and these have to be recognised from the outside instead.
     *
     * Only a path a write call spells out with its directory counts here. A bare
     * basename is too weak a claim to accuse a file of being generated on.
     */
    if (basename(file).startsWith('package')) continue;
    const writer = writerOf(file, null);
    if (writer !== null) {
      unmarked.push({ file, writtenBy: writer, command: commandFor(file, writer) });
      continue;
    }
    const command = commandWriting(file);
    if (command) unmarked.push({ file, writtenBy: command.runs, command: command.command });
  }

  /*
   * Every quotation below comes through `read`, which answers nothing for a file
   * that has been renamed away. A page about facts going stale must not be the
   * thing that fails the build when one does: the sentence built on a missing
   * file drops out of the page, and `test/provenance.test.ts` goes red saying
   * which one. Loud, and not fatal.
   */
  const architecture = contents(root, 'ARCHITECTURE.md', paths);
  const workflow = contents(root, '.github/workflows/sources.yml', paths);
  const decisionsTest = contents(root, 'apps/workbench/test/decision-numbers.test.ts', paths);
  const ledgerScript = contents(root, 'scripts/adr-ledger.mjs', paths);
  const diagramsTest = contents(root, 'apps/workbench/test/diagrams.test.ts', paths);
  const services = contents(root, 'apps/workbench/src/diagrams/Services.tsx', paths);

  const lockFile = contents(root, 'adr/decisions.lock.json', paths);
  const lock = (lockFile === '' ? {} : JSON.parse(lockFile)) as Record<
    string,
    { slugs?: string[]; decisions?: Record<string, string[]> }
  >;

  /** Every directory the tree has, so a test that walks one is read as reaching for it. */
  const directories = new Set<string>();
  for (const file of files) {
    for (let at = dirname(file); at !== '.' && !directories.has(at); at = dirname(at)) {
      directories.add(at);
    }
  }

  /**
   * The files and directories a test reaches for, as opposed to those it names.
   *
   * A path in a test is written from somewhere: `join(ROOT, 'apps/mobile/src')`
   * spells it out, and `join(APP, 'src')` does not, because the constant carrying
   * the rest of it is resolved at run time from `import.meta.url`. So each
   * literal is tried as written and again under the test's own workspace, and
   * only what the tree actually holds survives either way. A guess that names
   * nothing simply does not appear.
   */
  const readsOf = (text: string, from: string): string[] => {
    const found = new Set<string>();
    const near = packageOf(from);
    for (const line of text.split('\n')) {
      if (!READS.test(line)) continue;
      for (const hit of line.matchAll(PATH_LITERAL)) {
        const literal = hit[1].replace(/^(?:\.\.\/)+/, '');
        // As written first, and only then under the test's own workspace: the
        // app has an `AGENTS.md` of its own, so a test reading the root one
        // would otherwise be reported as reading both.
        const candidates =
          paths.has(literal) || directories.has(literal) ? [literal] : [`${near}/${literal}`];
        for (const candidate of candidates) {
          if (candidate.startsWith(dirname(from))) continue;
          if (paths.has(candidate) || directories.has(candidate)) found.add(candidate);
        }
      }
    }
    return [...found].sort();
  };

  const pinned: PinnedCheck[] = [];
  let cases = 0;
  for (const test of tests) {
    const text = testText.get(test) ?? '';
    const count = (text.match(/\b(?:it|test)(?:\.\w+)?\s*\(/g) ?? []).length;
    cases += count;
    if (!OPENS_A_FILE.test(text)) continue;
    // A fixture is the test's own input, written to be read by it. Opening one
    // is not holding anything to the repository, and counting it would put the
    // RSS parser's four sample feeds in the same list as a check on `AGENTS.md`.
    if (/__fixtures__/.test(text)) continue;
    const titles = [...text.matchAll(/\b(?:it|test)(?:\.\w+)?\(\s*['"`]([^'"`]{4,200})['"`]/g)];
    pinned.push({
      file: test,
      cases: count,
      reads: readsOf(text, test),
      titles: titles.map((hit) => hit[1]),
    });
  }

  const documents: DocumentPin[] = DOCUMENTS.map((document) => ({
    file: document.file,
    route: document.route,
    // Read, not merely named. A test's docstring cites the document its rule
    // comes from constantly, and counting those would put a dozen checks under
    // `AGENTS.md` when one of them opens the file.
    pinnedBy: pinned
      .filter((entry) => entry.reads.includes(document.file))
      .map((entry) => entry.file),
  }));

  return {
    generated: generated.sort((a, b) => a.file.localeCompare(b.file)),
    unmarked: unmarked.sort((a, b) => a.file.localeCompare(b.file)),
    // A tool outside this repository writes its own type shims, so a missing
    // generator here says nothing about this tree. Only a file naming a script
    // that ought to be in it counts as a claim nothing answers.
    orphaned: generated.filter((entry) => entry.writtenBy === null && entry.claims.includes('/')),
    documents,
    records: files.filter(isRecordFile).length,
    ledger: {
      records: Object.keys(lock).length,
      decisions: Object.values(lock).reduce((n, r) => n + Object.keys(r.decisions ?? {}).length, 0),
      texts: Object.values(lock).reduce(
        (n, r) => n + Object.values(r.decisions ?? {}).reduce((m, t) => m + t.length, 0),
        0,
      ),
      slugs: Object.values(lock).reduce((n, r) => n + (r.slugs?.length ?? 0), 0),
    },
    pinned,
    tests: { files: tests.length, cases },
    checkDuration: sentence(architecture, 'npm run check` at the root is'),
    sourcesCron: /cron:\s*'([^']+)'/.exec(workflow)?.[1] ?? null,
    // Both halves, because either one alone says nothing: the ledger reader can
    // still hold the command while no test calls it, and the test can still call
    // it while it has stopped reaching for the published copy.
    ledgerGuard:
      /'show',\s*`origin\/main:\$\{LEDGER_PATH\}`/.test(ledgerScript) &&
      /baselineLedger\(/.test(decisionsTest)
        ? `git show origin/main:${/LEDGER_PATH = '([^']+)'/.exec(ledgerScript)?.[1] ?? ''}`
        : null,
    portsRead:
      diagramsTest.includes('ts.createSourceFile') && diagramsTest.includes('CorePlatform')
        ? {
            file: 'apps/workbench/test/diagrams.test.ts',
            interface: 'CorePlatform',
            api: 'ts.createSourceFile',
          }
        : null,
    servicesClaim: flat(/[A-Z]\w+ content sources are live;[\s\S]*?\./.exec(services)?.[0] ?? '$'),
  };
}

/** The sentence of a document that opens with a given phrase, as one line. */
function sentence(document: string, opening: string): string | null {
  const at = document.indexOf(opening);
  if (at === -1) return null;
  const start = document.lastIndexOf('\n\n', at) + 2;
  const end = document.indexOf('. ', at);
  return flat(document.slice(start, end === -1 ? undefined : end + 1));
}

/** JSX and Markdown wrap where the line ends; a quotation of either has to not. */
function flat(text: string): string | null {
  const one = text.replace(/\s+/g, ' ').trim();
  return one === '$' || one === '' ? null : one;
}

/** A file this page quotes, read once, empty where the file has been renamed away. */
function contents(root: string, file: string, paths: Set<string>): string {
  return paths.has(file) ? readFileSync(join(root, file), 'utf8') : '';
}

/** A repository path as a link the document renderer re-points at the site or at GitHub. */
export function link(path: string, text = path): string {
  return `[${text}](${UP}${path})`;
}

/** A path in the typeface a path belongs in, linked. */
export function code(path: string): string {
  return link(path, `\`${path}\``);
}

/**
 * The file's own name, linked, for a column where the directory is noise.
 *
 * A table of five full paths wraps every cell onto three lines inside this
 * site's measure, and what a reader is looking for in a column of generators or
 * of checks is which one it is. The full path is a hover away and one click
 * away, and the page's prose spells it out wherever it matters.
 */
function short(path: string): string {
  return link(path, `\`${basename(path)}\``);
}

/** Bytes as a reader reads them, because 642110 says less than 627 KB. */
function size(bytes: number): string {
  return bytes < 1024 ? `${bytes} B` : `${Math.round(bytes / 1024)} KB`;
}

function table(headers: string[], rows: string[][]): string {
  const top = `| ${headers.join(' | ')} |\n| ${headers.map(() => '---').join(' | ')} |`;
  return `${top}\n${rows.map((row) => `| ${row.join(' | ')} |`).join('\n')}\n`;
}

/**
 * The checks this page's prose names, each looked up rather than described.
 *
 * A path typed here is the one kind of fact this page cannot generate: which
 * check is worth a paragraph is a judgement. What the paragraph then SAYS is
 * read — the case count, the case titles, the files it opens — so a check that
 * is renamed leaves a hole the page shows and `test/provenance.test.ts` fails on,
 * rather than a sentence that is quietly about nothing.
 */
export const NAMED_CHECKS = {
  tokens: 'apps/mobile/__tests__/tokens.test.ts',
  toolchain: 'apps/workbench/test/toolchain.test.ts',
  decisions: 'apps/workbench/test/decision-numbers.test.ts',
  diagrams: 'apps/workbench/test/diagrams.test.ts',
  colours: 'apps/mobile/__tests__/colour-tiers.test.ts',
  drift: 'packages/design-tokens/test/drift.test.ts',
  gallery: 'apps/mobile/__tests__/gallery-catalogue.test.ts',
  appSeam: 'apps/mobile/__tests__/localisation-seam.test.ts',
  coreSeam: 'packages/app-core/test/localisation-seam.test.ts',
  sources: 'apps/workbench/test/sources.test.ts',
  documents: 'apps/workbench/test/docs.test.ts',
} as const;

/** One named check, or nothing where it has been renamed or has stopped opening a file. */
function checkAt(provenance: Provenance, file: string): PinnedCheck | undefined {
  return provenance.pinned.find((entry) => entry.file === file);
}

/** The case of a check whose own title names a thing, quoted rather than summarised. */
function caseNaming(entry: PinnedCheck | undefined, word: string): string | null {
  const title = entry?.titles.find((name) => name.toLowerCase().includes(word.toLowerCase()));
  return title === undefined ? null : `“${title}”`;
}

/** A sentence that drops out entirely when the fact it is built from is gone. */
function when<T>(fact: T | null | undefined, write: (value: T) => string): string {
  return fact === null || fact === undefined ? '' : write(fact);
}

/**
 * The page.
 *
 * Long, and deliberately one document: the three tiers only mean anything beside
 * each other, and the exceptions only mean anything beside the tiers. Splitting
 * it into three pages would let a reader take the first and leave before the part
 * that says where it fails, which is the half worth publishing.
 */
export function provenanceMarkdown(p: Provenance): string {
  const inTree = p.generated.filter((entry) => entry.claims.includes('/'));
  const byTool = p.generated.filter((entry) => !entry.claims.includes('/'));
  const unread = p.documents.filter((document) => document.pinnedBy.length === 0);
  const tokens = checkAt(p, NAMED_CHECKS.tokens);
  const toolchain = checkAt(p, NAMED_CHECKS.toolchain);
  const diagrams = checkAt(p, NAMED_CHECKS.diagrams);
  const drift = checkAt(p, NAMED_CHECKS.drift);
  const gallery = checkAt(p, NAMED_CHECKS.gallery);
  const colours = checkAt(p, NAMED_CHECKS.colours);
  const documents = checkAt(p, NAMED_CHECKS.documents);

  return `# Provenance

Prose written about a codebase goes stale quietly, and nothing about it looks
wrong when it does. This repository answers that by producing as much as it can
from the sources, and there are three ways of doing that here. They are not
equally good, and the order below is the argument rather than a layout: each tier
is weaker than the one above it, and the weaker ones exist where the stronger one
could not reach.

This page is itself the first kind. It has no Markdown behind it:
${code(PROVENANCE_SOURCE.file)} scans the tree when the site is built, and the
${p.generated.length} generated files, ${p.pinned.length} checks,
${p.records} records and every path, count and quotation below were read out of it
then. What is typed is the argument.

## 1. Generated, and committed

The strongest, because there is no second copy to disagree with. A generated file
is written by a program from a source that is already in the repository, and it is
committed so that a fresh clone builds without running anything. Getting it wrong
is not a stale sentence, it is a file that differs from what its generator emits,
and that is a comparison a machine can make.

${p.generated.length} tracked files say so in their own first line. Each one names
what wrote it, which is how this table is built: the marker is read, the script it
names is found, and the write call in that script is matched against the path.

${table(
  ['File', 'Written by', 'Re-take with', 'Named by a check'],
  inTree.map((entry) => [
    `${code(entry.file)}<br>${entry.lines} lines, ${size(entry.bytes)}`,
    entry.writtenBy === null ? '**nothing in the tree**' : short(entry.writtenBy),
    entry.command === null ? '—' : `\`${entry.command}\``,
    entry.checkedBy.length === 0 ? '—' : entry.checkedBy.map(short).join('<br>'),
  ]),
)}
${
  byTool.length === 0
    ? ''
    : `A further ${byTool.length} carry a marker naming a tool rather than a script here — ${byTool
        .map((entry) => code(entry.file))
        .join(
          ', ',
        )}, written by \`${byTool[0].claims}\` as it builds. They are committed for the typechecker's benefit and nothing in this repository regenerates them.
`
}
**Two are checked by regenerating, which is the whole of the idea.**
${when(
  drift,
  () =>
    `${code(NAMED_CHECKS.drift)} runs the real generator over the real files, compares every byte and puts the committed ones back${when(caseNaming(drift, 'no drift'), (title) => `: ${title}`)}. `,
)}${when(
    gallery,
    () =>
      `${code(NAMED_CHECKS.gallery)} renders the component ids again from a walk of the app's components and compares the result with the committed file${when(caseNaming(gallery, 'no drift'), (title) => `: ${title}`)}. Forgetting to run a generator is therefore a red test rather than a file that has quietly stopped being true.`,
  )}

**A missing entry in the gallery is a compile error, and not in the generated
file.** ${code('apps/mobile/src/gallery/components.generated.ts')} exports the
union of every component id; ${code('apps/mobile/src/gallery/catalogue.tsx')} is
where a \`satisfies\` and three type aliases whose default parameter must resolve
to \`never\` turn a component with no entry into an error naming it. The generated
file supplies the vocabulary and the hand-written one carries the constraint,
which is worth keeping straight: regenerating the union is what the test above
covers, because the compiler cannot notice a name that was never extracted.

**The sources re-measure themselves.**
${code('apps/workbench/content/sources.measured.ts')} is the one generated file
whose source is not in the repository at all: it is a run against the live feeds,
and a browser cannot take it because they send no CORS header.
${code('.github/workflows/sources.yml')} takes it weekly${when(p.sourcesCron, (cron) => ` — \`${cron}\`, which is Monday mornings —`)} and opens a pull
request when a finding has moved. It reports and never gates: a source that is
down is somebody else's outage, and a pull request about a button must not turn
red because a newsroom is redeploying. What can fail is the run's own plumbing —
it counts the rows it wrote, and it runs \`npm run check\` over the file it would
commit, because a pull request opened with \`GITHUB_TOKEN\` starts no workflow and
nothing else would.

**Derived at build time, and deliberately not committed.** The core's reference
and the app's component list come from TypeDoc, run as a data extractor and never
as a site generator: it converts and emits no pages, and this site renders the
model with its own components. A generated documentation site would have arrived
with its own navigation and its own design and become the front door by accident.
The reduced model it leaves in
\`apps/workbench/content/api.generated.json\` is gitignored: it is derived, it is
large, and it would conflict on every rename. The site fails its build when it is
missing rather than publishing an empty reference, which is the same principle
one step further — a fact nobody can read is better than a fact that is wrong.

## 2. Read, not copied

Next strongest, and it applies where there is nothing to generate because the fact
is already written down once. The rule is then that it stays written down once and
is displayed from where it lives.

The site holds no copy of any document. ${code('apps/workbench/plugin/registry.ts')}
maps a path in the repository to a route, and
${code('apps/workbench/plugin/collect.ts')} reads and renders the file in place at
build time: ${p.documents.length} fixed documents and ${p.records} decision
records, ${p.documents.length + p.records} in all, with the links inside them
re-pointed at this site where it publishes the target and at the repository at the
built commit where it does not. A second copy of ${link('ARCHITECTURE.md')} would be
the one on the website, and it would be the one nobody edits.

The same rule, further down:

- **The decisions board** is built from the records themselves by
  ${code('apps/workbench/plugin/decisions.ts')}, including each claim a later
  record struck through and the record that struck it. Its numbers are not typed
  anywhere on the page.
- **The sources board** joins ${code('apps/workbench/content/sources.manifest.ts')},
  which carries the argument, onto the generated run, which carries every figure
  that moves. The measuring day comes out of the run and is typed nowhere.
- **The drawings** take their colours from the same token package the app does, so
  a diagram cannot fork the palette, and the record count in the diagram index is
  read off the documents rather than written into the caption.

## 3. Pinned by a check

The weakest of the three, and still worth having. Here the fact IS typed — in a
document, in a caption, in a constant — and a test opens the source and fails when
the two part. It is a copy with an alarm on it: the copy can still be wrong for as
long as it takes somebody to run the suite, and the alarm only rings for what
somebody thought to compare.

${p.pinned.length} test files do this, out of ${p.tests.files} in the repository,
carrying ${p.tests.cases} cases between them. A test that opens a file in the tree
is reading the source to hold something to it; one that does not is testing
behaviour.

${table(
  ['Check', 'Cases', 'What it opens'],
  p.pinned.map((entry) => [
    `${short(entry.file)}<br>${dirname(entry.file)}`,
    String(entry.cases),
    entry.reads.length === 0 ? '—' : entry.reads.map((read) => code(read)).join('<br>'),
  ]),
)}
Four of them are worth reading, because each one holds a different kind of fact.

${when(
  tokens,
  (t) =>
    `**A number in a document.** ${code(NAMED_CHECKS.tokens)} counts how many lines of the app write the two role colours this repository has not yet renamed, and holds ${link('AGENTS.md')} to that count in one of its ${t.cases} cases${when(caseNaming(t, 'AGENTS.md'), (title) => `: ${title}`)}. The figure was exact when it was typed, four short a week later, and nothing failed.\n`,
)}
${when(
  toolchain,
  (t) =>
    `**One fact written in four places.** ${code(NAMED_CHECKS.toolchain)} takes the Node version out of the root \`package.json\` and holds ${link('.nvmrc')}, every job in ${link('.github/workflows')} and the prose of ${link('README.md')} to it${when(caseNaming(t, 'readme'), (title) => `, including ${title}`)}. The README said 20.19 while everything else said 24.\n`,
)}
${when(
  diagrams,
  (d) =>
    `**A word in a picture.** ${when(p.portsRead, (ports) => `${code(ports.file)} parses ${code('packages/app-core/src/ports/index.ts')} with \`${ports.api}\`, takes the members of \`${ports.interface}\` as the ports, and holds every port name and every spelled count in the drawings to what it finds`)}. A regex over the file's text stood there first and was wrong in four silent ways at once. ${when(caseNaming(d, 'ports'), (title) => `Its first case is ${title}.`)} The drawings are prose in an \`<svg>\`, and nothing about a drawing looks wrong when a fifth port is declared.\n`,
)}
${when(
  colours,
  () =>
    `**A rule with a list of exceptions.** ${code(NAMED_CHECKS.colours)} fails on a colour primitive written where a semantic token was meant, against a per-file ratchet asserted in both directions: a use that arrives fails, and an excuse whose use has gone fails too, so the list cannot outlive what it excuses.\n`,
)}
### Which documents have a check under them

The published documents, and what reads each one. A document nothing reads is not
wrong; it is unheld, and the difference matters most for the ones carrying figures.

${table(
  ['Document', 'Held by'],
  p.documents.map((document) => [
    link(document.file),
    document.pinnedBy.length === 0 ? '**nothing**' : document.pinnedBy.map(short).join('<br>'),
  ]),
)}
${when(
  documents,
  (d) =>
    `Two sweeps cover what this table does not. ${code(NAMED_CHECKS.documents)} resolves every link in every document against the tree, one of its ${d.cases} cases, so a document naming a file that has moved fails rather than publishing a 404; and ${code(NAMED_CHECKS.decisions)} resolves every \`ADR NNNN §M\` citation in every tracked file against the records that exist today. Both hold what a document POINTS AT. Neither holds a word of what it says.\n`,
)}
## Deliberately weaker, and worth knowing why

### The ledger that must not be regenerable

${code('adr/decisions.lock.json')} records what every decision number has meant:
${p.ledger.records} records, ${p.ledger.decisions} numbered decisions, ${p.ledger.texts} headings between them${
    p.ledger.texts === p.ledger.decisions
      ? ' — no number has yet carried two'
      : ', because a number keeps every heading it has carried'
  }, and ${p.ledger.slugs} filenames. \`npm run adr:lock\` only ever appends to it. It is
the one derived file in this repository that must NOT be regenerable, because
regenerating it is exactly the operation that would accept a renumbering without
saying so.

${when(
  p.ledgerGuard,
  (guard) =>
    `What holds it is a comparison with the published copy, \`${guard}\`, in ${code(NAMED_CHECKS.decisions)}: the working tree's ledger has to be an EXTENSION of the one on the default branch, never a revision of it.`,
)} That does not make a renumbering impossible — a swap put through \`adr:lock\`
appends and passes — it makes one impossible to do quietly, because the append
cannot later be taken out and the diff shows both numbers carrying each other's
heading. Every other check on the ledger reads the working tree alone, and a
renumbering that edits the records and the ledger in one pass leaves a working
tree that agrees with itself. Those checks are kept for the accident and the
half-finished edit. They are not a defence against somebody who means it.

### One figure, one place, and a pointer from everywhere else

Where a fact cannot be re-taken by a machine, the arrangement is to keep it in one
document and have the others point at it. How long \`npm run check\` takes is the
example: it is measured in ${link('ARCHITECTURE.md')} and nowhere else, and
${link('AGENTS.md')} says so rather than repeating the number.

${when(p.checkDuration, (measured) => `> ${measured}\n`)}
This is the weaker arrangement and the reason is worth stating: a pointer stops
two copies parting, and nothing about it stops the one copy going stale. That
sentence said ten for months. A figure that depends on the machine it was measured
on should be read as a bound rather than a reading.

### Facts measured against the outside world

A figure taken against somebody else's service cannot be held to anything in this
repository, so the answer is to re-take it rather than to check it. That is the
weekly sources run above. It reports and never gates, which is not laxity: a
scheduled job that opens a pull request runs on nobody's critical path, and the
alternatives were a job that always exits 0, which trains everybody to stop
opening it, and \`continue-on-error\`, which cannot tell a source being down from
the script being broken.

## Where it fails

The list above is the flattering half. These are the places where a fact is typed
with nothing under it, or where the machinery on this page cannot see.

${
  p.unmarked.length === 0
    ? ''
    : `**${p.unmarked.length} files are generated, committed, and say nothing about it.** A marker is what tells somebody opening a file that editing it is a wasted afternoon, and JSON cannot carry a comment, which is the reason rather than the excuse.

${table(
  ['File', 'Written by', 'Re-take with'],
  p.unmarked.map((entry) => [
    code(entry.file),
    entry.writtenBy.startsWith('npm') || entry.writtenBy.includes(' ')
      ? 'a command, not a script in the tree'
      : code(entry.writtenBy),
    entry.command === null ? '—' : `\`${entry.command}\``,
  ]),
)}`
}
${
  p.orphaned.length === 0
    ? ''
    : `**${p.orphaned.length} files claim a generator this repository has not got.** ${p.orphaned
        .map((entry) => `${code(entry.file)} names \`${entry.claims}\``)
        .join(
          '; ',
        )}. Either the generator was renamed and the marker was not, or the file stopped being generated and is now hand-edited under a header that says it is not.

`
}${
    unread.length === 0
      ? ''
      : `**${unread.length} published documents are read by no check**: ${unread
          .map((document) => link(document.file))
          .join(
            ', ',
          )}. Every figure in them is a typed fact with nothing under it. ${link('ARCHITECTURE.md')} is the one that matters most, because it is where this repository keeps the figures the other documents point at.

`
  }${when(
    p.servicesClaim,
    (claim) =>
      `**A drawing counts the sources by hand.** ${code('apps/workbench/src/diagrams/Services.tsx')} says: “${claim}” ${code(NAMED_CHECKS.diagrams)} holds the port count and the file count in the drawings to the core, and nothing holds this one to ${code('apps/workbench/content/sources.manifest.ts')}, which counts the same things beside it. The sources board and the drawing can disagree, and only a reader would notice.\n`,
  )}
**What the scan behind this page cannot see.** A generated file is found by its
marker, so one that carries none is found only if a write call in a \`scripts/\` or
\`tools/\` directory spells its path out. A generator somewhere else, or one that
builds its path from pieces at run time, is invisible here. A check is recognised
by opening a file in the tree, so a test that holds a constant to another constant
through an import — which is stronger, not weaker — does not appear in the table
above at all, and one that assembles its paths at run time appears there with
nothing in its last column. And the tiers say where a fact comes from, never whether it is true:
a generator can be wrong, and then it is wrong everywhere at once.
`;
}
