/**
 * The English catalogue, compiled from `en.json` by `npm run compile`.
 *
 * Generated — do not edit. `test/catalogue.test.ts` runs the generator and compares,
 * so an edit here is undone by the next run and reported by the check before that.
 *
 * It is the `defaultMessage` of every descriptor with the descriptions dropped, which
 * is exactly the shape the provider wants. English therefore ships as data like every
 * other language rather than as a fallback nobody chose.
 */
export const en: Record<string, string> = {
  "article.documentTitle": "Article",
  "article.frameTitle": "Article",
  "article.kickerFallback": "Investigation",
  "article.loadFailed": "The article could not be loaded",
  "article.openInBrowser": "Open in the browser",
  "article.readingTime": "{count, plural, one {# min read} other {# min read}}",
  "article.removeSaved": "Saved, remove",
  "article.retry": "Try again",
  "article.retryHint": "A second attempt may help.",
  "article.save": "Save the article",
  "article.share": "Share the article",
  "atlas.mapPlaceholder": "Map detail (static)",
  "atlas.recentHeading": "Most recently reported",
  "atlas.report": "Report a demolition on abriss-atlas.de",
  "atlas.stats": "{reports, plural, one {One reported demolition} other {# reported demolitions}} in {cities, plural, one {one city} other {# cities}} (DE/CH)",
  "backstage.allFromBackstage": "Everything from Backstage",
  "backstage.diaryLabel": "Research diary",
  "backstage.earlyAccessBadge": "Backstage · read it earlier",
  "backstage.earlyAccessLabel": "Read it earlier",
  "backstage.eventsLabel": "Dates",
  "backstage.letterLabel": "Backstage letter",
  "backstage.publicFrom": "Public from {date}",
  "backstage.publisherLabel": "Publishing house",
  "backstage.qaLabel": "Questions and answers",
  "backstage.readNow": "Read it now",
  "backstage.reportTitle": "Quarterly report",
  "backstage.shop": "To the shop",
  "callout.card.contributed": "✓ You have contributed",
  "callout.contributeAgain": "Send another tip",
  "callout.crowdnewsroom.count": "{count, plural, one {One contribution} other {# contributions}}",
  "callout.crowdnewsroom.countSoFar": "{count, plural, one {One contribution} other {# contributions}} so far",
  "callout.crowdnewsroom.cta": "Take part",
  "callout.detail.contributed": "✓ You have contributed already, thank you! More tips are welcome.",
  "callout.detail.cta": "Take part",
  "callout.detail.dataUse": "What happens to your data?",
  "callout.detail.noSlug": "No identifier was passed.",
  "callout.detail.responses": "{count, plural, one {One contribution} other {# contributions}} so far",
  "callout.detail.unknownHeadline": "This callout does not exist",
  "callout.detail.unknownSlug": "Unknown identifier \"{slug}\".",
  "callout.detail.whoAsks": "Who is asking?",
  "callout.screenTitle": "Callout",
  "callout.survey.count": "{count, plural, one {One response} other {# responses}}",
  "callout.survey.countSoFar": "{count, plural, one {One response} other {# responses}} so far",
  "callout.survey.cta": "Take part",
  "callout.survey.kicker": "Survey",
  "callout.teaser.ctaAccessibility": "{cta}: {title}",
  "callout.teaser.kicker": "Take part · {kicker}",
  "claim.credibility": "Reliability: {level}",
  "claim.noId": "No identifier was passed.",
  "claim.noSources": "No sources yet. The community is gathering them.",
  "claim.quote": "\"{quote}\"",
  "claim.screenTitle": "Claim",
  "claim.sourcesHeading": "Source assessment",
  "claim.stage.checked": "Checked",
  "claim.stage.checking": "Being checked",
  "claim.stage.submitted": "Submitted",
  "claim.submitOwn": "Submit a tip of your own (in the Faktenforum)",
  "claim.unknownHeadline": "This claim does not exist",
  "claim.unknownId": "Unknown identifier \"{id}\".",
  "core.audio.interrupted": "Playback was interrupted. Check your connection and try again.",
  "core.audio.startFailed": "Playback could not be started. Check your connection and try again.",
  "core.audio.unsupportedPlatform": "Playback is not available on this platform.",
  "core.rating.false": "False",
  "core.rating.manipulated": "Manipulated",
  "core.rating.misleading": "Misleading",
  "core.rating.missingContext": "Missing context",
  "core.rating.mostlyFalse": "Mostly false",
  "core.rating.mostlyTrue": "Mostly true",
  "core.rating.partlyFalse": "Partly false",
  "core.rating.satire": "Satire",
  "core.rating.true": "True",
  "core.rating.unproven": "Unproven",
  "core.reader.byline": "by {authors}",
  "core.reader.factcheckBadge": "Fact check",
  "core.reader.readingTime": "{minutes} min read",
  "core.reader.support": "Made possible by supporters like you. Thank you for being here.",
  "diary.noId": "No identifier was passed.",
  "diary.notFound": "This entry does not exist",
  "diary.screenTitle": "Research diary",
  "diary.unknownId": "Unknown identifier \"{id}\".",
  "discover.openSearch": "Open search",
  "discover.searchPlaceholder": "Investigations, fact checks, projects …",
  "discover.title": "Discover",
  "faktenforum.lead": "The community checks claims together with the CORRECTIV newsroom. Have a look at what is being worked on.",
  "faktenforum.quote": "\"{quote}\"",
  "faktenforum.submitted": "{shortId} · submitted {date}",
  "form.answerPlaceholder": "Your answer …",
  "form.back": "Back",
  "form.cancel": "Cancel",
  "form.contributors": "{count, plural, one {One person has} other {# people have}} contributed so far.",
  "form.fileAttached": "{file} attached ✓",
  "form.filePick": "Choose a photo or document (simulated)",
  "form.moreCallouts": "See more ways to take part",
  "form.next": "Next",
  "form.noSlug": "No callout was given.",
  "form.screenTitle": "Participation form",
  "form.step": "Step {current} of {total}",
  "form.submit": "Send",
  "form.thanksHeadline": "Thank you for your contribution!",
  "form.thanksLead": "Your contribution goes into the investigation. The newsroom reviews every tip. We will get in touch if anything is unclear.",
  "form.unknownHeadline": "This form does not exist",
  "form.unknownSlug": "Unknown callout \"{slug}\".",
  "gate.checking": "Checking your membership …",
  "gate.emailHeading": "Email",
  "gate.emailLabel": "Email address",
  "gate.emailPlaceholder": "name@example.org",
  "gate.failure.unreachable": "correctiv.org cannot be reached at the moment. Please try again in a few minutes.",
  "gate.failure.wrongCredentials": "That email address and password do not match. Please check both.",
  "gate.forgot": "Forgotten your password?",
  "gate.headline": "For everyone who carries CORRECTIV.",
  "gate.join": "Become a member with a contribution",
  "gate.lead": "This app is the place for members who contribute. Your account is the same one you use on correctiv.org.",
  "gate.noAccess.accessLapsed": "Trial, ended on {date}",
  "gate.noAccess.accessNone": "Not included",
  "gate.noAccess.accessRow": "App access",
  "gate.noAccess.headline": "Good to have you with us.",
  "gate.noAccess.lapsed": "Your trial ended on {date}. Thank you for trying the app. With a contribution it carries on here, with everything you already know.",
  "gate.noAccess.lead": "The app is part of membership with a contribution.",
  "gate.noAccess.recheck": "Check again",
  "gate.noAccess.resume": "Set a contribution",
  "gate.noAccess.signedInAs": "Signed in as {email}",
  "gate.noAccess.simulated": "Nothing is transmitted. After \"{button}\", \"{recheck}\" finds a membership with a contribution.",
  "gate.noAccess.switchAccount": "Sign in with a different account",
  "gate.noAccess.tier": "Your account is on the free tier. It keeps everything on correctiv.org open to you. The app comes with the contribution: it funds the investigations, and in return there is audio, video and formats that exist only here.",
  "gate.noAccess.tierRow": "Your tier",
  "gate.noAccess.tierTrial": "Trial",
  "gate.noAccess.upgrade": "Extend membership",
  "gate.passwordHeading": "Password",
  "gate.passwordLabel": "Enter password",
  "gate.passwordPlaceholder": "Your password",
  "gate.simulated": "Nothing is transmitted. Every address signs in: with \"frei\" as the free tier without app access, with \"test\" during the trial, with \"lokal\" through the local bundle. A password shorter than four characters fails.",
  "gate.simulatedHeading": "Simulated",
  "gate.submit": "Sign in",
  "home.allIssues": "All issues",
  "home.allSpotlightIssues": "All Spotlight issues",
  "home.factCheckBadge": "Fact check",
  "home.factChecks": "Fact checks",
  "home.impactBody": "CORRECTIV is non-profit. Your contribution funds the investigations you find here.",
  "home.impactHeadline": "Made possible by supporters like you",
  "home.latestResearch": "Latest investigations",
  "home.offlineArticles": "No connection. You are seeing saved articles.",
  "home.spotlightLead": "The day in brief, every morning in the newsletter.",
  "home.spotlightOffline": "No connection. You are seeing saved issues.",
  "home.spotlightOfflineArchive": "No connection. You are seeing saved issues from the end of the summer.",
  "home.viewAll": "See all",
  "home.viewEverything": "See everything",
  "mediathek.fromBackstage": "From Backstage",
  "mediathek.listeners": "{count, plural, one {# listener} other {# listeners}}",
  "mediathek.live": "Live",
  "mediathek.liveSubtitle": "24/7 from Bottrop, by young people for young people",
  "mediathek.offlineEpisodes": "No connection. You are seeing sample episodes.",
  "mediathek.pauseEpisode": "Pause {title}",
  "mediathek.pauseRadio": "Pause the radio",
  "mediathek.playEpisode": "Play {title}",
  "mediathek.playRadio": "Play the radio",
  "mediathek.podcasts": "Podcasts",
  "mediathek.radioPlaying": "Salon5 Radio is on air",
  "mediathek.radioTapToListen": "24/7 from Bottrop · tap to listen",
  "mediathek.streamUnavailable": "Stream cannot be reached",
  "mediathek.videoOfTheDay": "Video of the day",
  "mediathek.videosUnavailable": "Videos cannot be reached at the moment.",
  "notFound.headline": "This page does not exist",
  "notFound.home": "To the home screen",
  "notFound.lead": "The link leads nowhere. The article may have been moved, or the address may be incomplete.",
  "notFound.overline": "Error 404",
  "notFound.screenTitle": "Page not found",
  "onboarding.done": "Done",
  "onboarding.interests.headline": "What interests you?",
  "onboarding.interests.lead": "Your selection orders the home screen.",
  "onboarding.mission.donations": "Donation-funded: carried by thousands",
  "onboarding.mission.headline": "Investigations for society",
  "onboarding.mission.nonprofit": "Non-profit: nobody owns us",
  "onboarding.next": "Next",
  "onboarding.participate.headline": "Investigations you take part in",
  "onboarding.participate.lead": "In the CrowdNewsroom thousands of people contribute to investigations. In the Faktenforum the community checks claims. You find both in the \"Mitmachen\" tab.",
  "onboarding.push.description": "For new investigations and callouts (simulated)",
  "onboarding.push.label": "Notifications",
  "onboarding.screenTitle": "Welcome",
  "onboarding.skip": "Skip",
  "onboarding.start": "Let's go",
  "participate.activeCallouts": "Open callouts",
  "participate.atlasAction": "See the atlas",
  "participate.atlasHeading": "Document demolitions",
  "participate.atlasLead": "Which buildings are disappearing? {reports, plural, one {One report} other {# reports}} from {cities, plural, one {one city} other {# cities}} in Germany and Switzerland.",
  "participate.claimChecked": "Checked: {verdict}",
  "participate.claimChecking": "Being checked",
  "participate.claimNoVerdict": "closed",
  "participate.claimSubmitted": "Submitted",
  "participate.communityNote": "In the community area you discuss investigations with other members, and soon in the app as well.",
  "participate.forumAction": "See the claims",
  "participate.forumHeading": "Checking claims together",
  "participate.forumLead": "The community checks claims from around the web, guided by the newsroom. Right now {count, plural, one {one claim is} other {# claims are}} being worked on.",
  "participate.lead": "Investigations are made with you. Your tips, your observations and your checks are what make them possible.",
  "participate.tipAction": "Open WhatsApp",
  "participate.tipHeading": "Fact-check tip by WhatsApp",
  "participate.tipLabel": "Send a tip",
  "participate.tipLead": "Seen a suspicious claim? Send it straight to the fact-checking desk.",
  "participate.title": "Take part",
  "player.changeSpeed": "Change the speed",
  "player.close": "Close the player",
  "player.documentTitle": "Player",
  "player.error": "Error",
  "player.live": "● LIVE",
  "player.liveNote": "Live stream. Salon5 is on air around the clock.",
  "player.liveSubtitle": "● LIVE · 24/7 from Bottrop",
  "player.loading": "Loading …",
  "player.nothingPlaying": "Nothing is playing.",
  "player.open": "Open the player",
  "player.pause": "Pause",
  "player.play": "Play",
  "player.position": "Playback position",
  "player.radioSubtitle": "24/7 from Bottrop",
  "player.radioTitle": "Salon5 Radio",
  "player.stop": "Stop playback",
  "profile.area.section": "Your area",
  "profile.club.fallbackName": "Member",
  "profile.club.tierSince": "{tier} · since {date}",
  "profile.impact.anonymous": "Your contribution makes these investigations possible.{articles, select, some { Among others, these:} other {}}",
  "profile.impact.section": "Your impact",
  "profile.impact.since": "You have been supporting CORRECTIV {months, plural, one {for a short while} other {for # months}}.{articles, select, some { Among others, these investigations were made possible:} other {}}",
  "profile.membership.localAreas": "Local newsletters",
  "profile.membership.manageAccount": "Manage account",
  "profile.membership.note": "You manage your contribution, your payment method and your data in your account on correctiv.org.",
  "profile.membership.section": "Your membership",
  "profile.membership.source": "Access through",
  "profile.membership.tier": "Tier",
  "profile.membership.validUntil": "Runs until",
  "profile.nav.backstage": "Your Backstage",
  "profile.nav.backstageSubtitle": "Diaries, bonus episodes, events",
  "profile.nav.clubAccessibility": "{title}, Club",
  "profile.nav.reportSubtitle": "Where your contribution goes, broken down transparently.",
  "profile.nav.saved": "Saved articles",
  "profile.nav.savedCount": "{count, plural, =0 {Nothing saved yet} one {# article} other {# articles}}",
  "profile.nav.settings": "App settings",
  "profile.nav.settingsSubtitle": "Notifications, text size, About CORRECTIV",
  "profile.newsletter.klima": "The climate investigations of the week",
  "profile.newsletter.section": "Newsletter",
  "profile.newsletter.spotlight": "The most important stories, on weekday mornings",
  "profile.newsletter.spotlightCh": "Investigations from Switzerland",
  "profile.saved.empty": "Nothing saved yet. Tap the bookmark in an article to keep it here.",
  "profile.saved.remove": "Remove {title}",
  "profile.saved.savedOn": "saved {date}",
  "profile.saved.title": "Saved articles",
  "profile.source.localBundle": "your local subscription",
  "profile.source.paid": "your contribution",
  "profile.source.trial": "your trial",
  "profile.tier.free": "Free membership",
  "profile.tier.paid": "Membership with a contribution",
  "profile.tier.soli": "Solidarity membership",
  "profile.title": "Profile",
  "project.comingSoon": "Coming soon",
  "project.comingSoonBody": "{name} is just starting. The first pieces appear here as soon as they are published.",
  "project.feedFailed": "The pieces could not be loaded.",
  "project.joinLocalNetwork": "Join the local network",
  "project.latestPosts": "Latest pieces",
  "project.listenRadio": "Listen to Salon5 Radio",
  "project.noId": "No identifier was passed.",
  "project.notFound": "This project does not exist",
  "project.screenTitle": "Project",
  "project.tipWhatsapp": "Send a tip on WhatsApp",
  "project.unknownId": "Unknown identifier \"{id}\".",
  "search.articlesHeading": "Articles",
  "search.fieldLabel": "Search term",
  "search.hint": "Search across investigations, fact checks, projects, podcasts and ways to take part.",
  "search.noResults": "No hits for \"{query}\".",
  "search.placeholder": "Search …",
  "search.projectsHeading": "From the projects",
  "search.screenTitle": "Search",
  "series.noId": "No identifier was passed.",
  "series.notFound": "This series does not exist",
  "series.screenTitle": "Podcast series",
  "series.unknownId": "Unknown identifier \"{id}\".",
  "settings.about.body": "CORRECTIV is a non-profit, independent centre for investigative journalism. Investigations for society, funded by people like you.",
  "settings.about.imprint": "Legal notice",
  "settings.about.privacy": "Privacy",
  "settings.about.section": "About CORRECTIV",
  "settings.about.website": "Open correctiv.org",
  "settings.access.localBundle": "Local bundle",
  "settings.access.none": "No app access",
  "settings.access.paid": "Membership with a contribution",
  "settings.access.trial": "Trial",
  "settings.account.section": "Account",
  "settings.account.signOut": "Sign out",
  "settings.account.signedOut": "Not signed in",
  "settings.appearance.dark": "Dark mode",
  "settings.appearance.followSystem": "Follow the system setting",
  "settings.appearance.section": "Appearance",
  "settings.demo.done": "✓ Reset. Restart the app for the onboarding.",
  "settings.demo.note": "For demonstrations: resets interests and onboarding. Your account stays signed in.",
  "settings.demo.reset": "Reset the demo state",
  "settings.demo.section": "Demo",
  "settings.notifications.push": "Push notifications",
  "settings.notifications.pushDescription": "New investigations and calls to take part (simulated)",
  "settings.notifications.section": "Notifications",
  "settings.textSize.followSystem": "Follow the system setting",
  "settings.textSize.noteManual": "Applies to the whole app, articles included, in place of your device's text size. For larger text, follow the system setting and choose the size on your device.",
  "settings.textSize.noteSystem": "The whole app, articles included, uses the text size set on your device.",
  "settings.textSize.option": "Text size {scale}",
  "settings.textSize.section": "Text size",
  "settings.title": "Settings",
  "ui.back": "Back",
  "ui.previewDraft": "Preview draft, not the published app",
  "ui.tabDiscover": "Discover",
  "ui.tabHome": "Home",
  "ui.tabMediathek": "Mediathek",
  "ui.tabParticipate": "Take part",
  "ui.tabProfile": "Profile",
  "video.cardLabel": "Video: {title}",
  "video.duration": "{count, plural, one {# min} other {# min}}",
  "video.frameTitle": "Video",
  "video.kicker": "Video",
  "video.loading": "Loading …",
  "video.newEpisode": "New episode",
  "video.none": "No video selected.",
  "video.screenTitle": "Video",
  "video.today": "Today",
  "video.unavailable": "Video unavailable",
  "video.views": "{count, plural, one {# view} other {# views}}",
  "video.watchOn": "Watch on {host}",
  "video.watchOriginal": "Watch the original",
  "video.yesterday": "Yesterday",
};
