// AUTO-GENERATED by apps/mobile/scripts/generate-home-settings.mjs — do not edit by hand.
// Source: apps/mobile/src/lib/home/blocks.ts · Regenerate: npm run home-settings

import type { BlockCategory } from './block-category';
import type { ConfigurableScreen } from './screen-layout';

/**
 * Block name, as the document writes it, to the family it belongs to. Every block the
 * app can draw has an entry, so this is also the roll-call a picker reads.
 *
 * Declared beside the blocks in `apps/mobile/src/lib/home/blocks.ts` and carried here for the reason the settings
 * are: the core cannot import the app. ADR 0073 §2.
 */
export const MODULE_CATEGORIES: Readonly<Record<string, BlockCategory>> = {
  'home-header': 'struktur',
  'feed-status': 'struktur',
  'discover-header': 'struktur',
  'search-entry': 'struktur',
  'mediathek-header': 'struktur',
  'participate-header': 'struktur',
  'impact-footer': 'struktur',
  'article-hero': 'recherche',
  'latest-research': 'recherche',
  'spotlight-briefing': 'recherche',
  'topic-rail': 'recherche',
  'project-directory': 'recherche',
  'faktencheck-rail': 'faktencheck',
  'faktenforum-card': 'faktencheck',
  'tip-card': 'faktencheck',
  'mediathek-reihe': 'medien',
  'live-radio-banner': 'medien',
  'podcast-rail': 'medien',
  'gespraech-rail': 'medien',
  'funfacts-rail': 'medien',
  'bonus-audio-list': 'medien',
  'callout-teaser': 'mitmachen',
  'callout-list': 'mitmachen',
  'atlas-card': 'mitmachen',
  'community-note': 'mitmachen',
  'early-access-card': 'club',
  'backstage-teaser': 'club',
  'profile-club-card': 'club',
  'profile-membership': 'club',
  'profile-impact': 'club',
  'profile-area': 'club',
  'profile-newsletter': 'club',
};

/**
 * The few blocks bound to one screen, and the screen each one is. A block that is not
 * here may be placed on every configurable screen, which is ADR 0073 §1; the parser
 * refuses the rest with `section-module-not-on-screen` (ADR 0073 §3).
 */
export const SCREEN_BOUND_BLOCKS: Readonly<Record<string, ConfigurableScreen>> = {
  'home-header': 'home',
  'discover-header': 'entdecken',
  'mediathek-header': 'mediathek',
  'participate-header': 'mitmachen',
};
