// AUTO-GENERATED by apps/mobile/scripts/generate-home-settings.mjs — do not edit by hand.
// Source: apps/mobile/src/lib/home/blocks.ts · apps/mobile/src/lib/screenIcons.ts · Regenerate: npm run home-settings

import type { BlockCategory } from './block-category';
import type { ConfigurableScreen, ScreenIcon } from './screen-layout';

/**
 * Block name, as the document writes it, to the family it belongs to. Every block the
 * app can draw has an entry, so this is also the roll-call a picker reads.
 *
 * Declared beside the blocks in `apps/mobile/src/lib/home/blocks.ts` and carried here for the reason the settings
 * are: the core cannot import the app. ADR 0073 §2.
 */
export const MODULE_CATEGORIES: Readonly<Record<string, BlockCategory>> = {
  'home-header': 'struktur',
  'feed-status': 'struktur',
  'discover-header': 'struktur',
  'search-entry': 'struktur',
  'mediathek-header': 'struktur',
  'participate-header': 'struktur',
  'impact-footer': 'struktur',
  'article-hero': 'recherche',
  'latest-research': 'recherche',
  'spotlight-briefing': 'recherche',
  'topic-rail': 'recherche',
  'project-directory': 'recherche',
  'faktencheck-rail': 'faktencheck',
  'faktenforum-card': 'faktencheck',
  'tip-card': 'faktencheck',
  'mediathek-reihe': 'medien',
  'live-radio-banner': 'medien',
  'podcast-rail': 'medien',
  'gespraech-rail': 'medien',
  'funfacts-rail': 'medien',
  'bonus-audio-list': 'medien',
  'callout-teaser': 'mitmachen',
  'callout-list': 'mitmachen',
  'atlas-card': 'mitmachen',
  'community-note': 'mitmachen',
  'early-access-card': 'club',
  'backstage-teaser': 'club',
  'profile-club-card': 'club',
  'profile-membership': 'club',
  'profile-impact': 'club',
  'profile-area': 'club',
  'profile-newsletter': 'club',
};

/**
 * The few blocks bound to one screen, and the screen each one is. A block that is not
 * here may be placed on every configurable screen, which is ADR 0073 §1; the parser
 * refuses the rest with `section-module-not-on-screen` (ADR 0073 §3).
 */
export const SCREEN_BOUND_BLOCKS: Readonly<Record<string, ConfigurableScreen>> = {
  'home-header': 'home',
  'discover-header': 'entdecken',
  'mediathek-header': 'mediathek',
  'participate-header': 'mitmachen',
};

/**
 * Icon key, as a screen document names it, to the three native names it is drawn with.
 * The set a document may choose out of (ADR 0075 §4), and the list the workbench's picker
 * reads rather than inventing a second one. A key that is not here is reported by the
 * parser and dropped, and the screen draws the fallback beside it in `screen-layout.ts`.
 *
 * Declared in `apps/mobile/src/lib/screenIcons.ts` — in a file of its own because the generator reads it by
 * importing it under Node's type stripping, and that leaves no room for an ordinary
 * import. ADR 0075 §4.
 */
export const SCREEN_ICONS: Readonly<Record<string, ScreenIcon>> = {
  'home': {
    sf: { default: 'house', selected: 'house.fill' },
    md: { default: 'home', selected: 'home' },
    ionicon: { active: 'home', inactive: 'home-outline' },
  },
  'compass': {
    sf: { default: 'safari', selected: 'safari.fill' },
    md: { default: 'explore', selected: 'explore' },
    ionicon: { active: 'compass', inactive: 'compass-outline' },
  },
  'play': {
    sf: { default: 'play.circle', selected: 'play.circle.fill' },
    md: { default: 'play_circle', selected: 'play_circle' },
    ionicon: { active: 'play-circle', inactive: 'play-circle-outline' },
  },
  'people': {
    sf: { default: 'person.2', selected: 'person.2.fill' },
    md: { default: 'groups', selected: 'groups' },
    ionicon: { active: 'people', inactive: 'people-outline' },
  },
  'person': {
    sf: { default: 'person.crop.circle', selected: 'person.crop.circle.fill' },
    md: { default: 'account_circle', selected: 'account_circle' },
    ionicon: { active: 'person', inactive: 'person-outline' },
  },
  'more': {
    sf: { default: 'ellipsis.circle', selected: 'ellipsis.circle.fill' },
    md: { default: 'more_horiz', selected: 'more_horiz' },
    ionicon: { active: 'ellipsis-horizontal-circle', inactive: 'ellipsis-horizontal-circle-outline' },
  },
  'default': {
    sf: { default: 'square.grid.2x2', selected: 'square.grid.2x2.fill' },
    md: { default: 'apps', selected: 'apps' },
    ionicon: { active: 'apps', inactive: 'apps-outline' },
  },
};
