// AUTO-GENERATED by apps/mobile/scripts/generate-home-settings.mjs — do not edit by hand.
// Source: apps/mobile/src/lib/home/conditions.ts · Regenerate: npm run home-settings

import type { Audience } from './home-audience';

/**
 * Module name, as the document writes it, to the audience it is for unless the document
 * says otherwise. A module that is not here is for everyone.
 *
 * Declared beside the modules in `apps/mobile/src/lib/home/conditions.ts` and carried here for the
 * reason the settings are: the fold is the core's, and the core cannot import the app.
 * ADR 0060 §2 is the record.
 */
export const MODULE_AUDIENCES: Readonly<Record<string, Audience>> = {
  'early-access-card': 'paying-members',
};
