// AUTO-GENERATED by apps/mobile/scripts/generate-home-settings.mjs — do not edit by hand.
// Source: apps/mobile/src/lib/home/settings.ts · Regenerate: npm run home-settings

import type { SettingSpec } from './home-settings';

/**
 * Module name, as the document writes it, to the settings it understands.
 *
 * The declarations live beside the modules that read them, in `apps/mobile/src/lib/home/settings.ts`,
 * and this file is what carries them across the boundary the other direction cannot be
 * crossed in — the core is a dependency of the app, so the app cannot be a dependency of
 * the core. ADR 0045 §9 is the record; the script named above is the mechanism.
 *
 * Nothing here imports the app, which is the point: `parseHomeLayout` answers the same
 * way in a test, in a check, in the configurator and in the app, with nothing booted
 * first.
 */
export const MODULE_SETTINGS: Readonly<Record<string, readonly SettingSpec[]>> = {
  'article-hero': [{ key: 'pin', kind: 'article', fallback: null }],
  'latest-research': [{ key: 'count', kind: 'count', min: 1, max: 8, fallback: 5 }],
  'faktencheck-rail': [{ key: 'count', kind: 'count', min: 1, max: 12, fallback: 8 }],
};
