// AUTO-GENERATED by apps/mobile/scripts/generate-home-settings.mjs — do not edit by hand.
// Source: apps/mobile/src/lib/home/screens.ts · Regenerate: npm run home-settings

import type { ConfigurableScreen } from './screen-layout';

/**
 * Block name, as the document writes it, to the screens it may be arranged on.
 *
 * Declared beside the blocks in `apps/mobile/src/lib/home/screens.ts` and carried here for the reason the settings
 * are: the parser is the core's, and the core cannot import the app. ADR 0054 §5.
 */
export const MODULE_SCREENS: Readonly<Record<string, readonly ConfigurableScreen[]>> = {
  'home-header': ['home'],
  'feed-status': ['home'],
  'article-hero': ['home'],
  'spotlight-briefing': ['home'],
  'early-access-card': ['home'],
  'latest-research': ['home'],
  'faktencheck-rail': ['home', 'entdecken'],
  'callout-teaser': ['home'],
  'mediathek-reihe': ['home'],
  'backstage-teaser': ['home'],
  'impact-footer': ['home'],
  'discover-header': ['entdecken'],
  'search-entry': ['entdecken'],
  'topic-rail': ['entdecken'],
  'project-directory': ['entdecken'],
  'mediathek-header': ['mediathek'],
  'live-radio-banner': ['mediathek'],
  'podcast-rail': ['mediathek'],
  'gespraech-rail': ['mediathek'],
  'funfacts-rail': ['mediathek'],
  'bonus-audio-list': ['mediathek'],
  'participate-header': ['mitmachen'],
  'callout-list': ['mitmachen'],
  'faktenforum-card': ['mitmachen'],
  'atlas-card': ['mitmachen'],
  'tip-card': ['mitmachen'],
  'community-note': ['mitmachen'],
  'profile-club-card': ['profil'],
  'profile-membership': ['profil'],
  'profile-impact': ['profil'],
  'profile-area': ['profil'],
  'profile-newsletter': ['profil'],
};
